Description: >
    This template deploys elastic file system for use across the infrastructure.

Parameters:
    CompanyName:
        Description: Used to name space company buckets
        Type: String
        Default: transin
        
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: transin

    # EFS
    PerformanceMode:
      Type: String
      Default: generalPurpose
      AllowedValues:
      - generalPurpose
      - maxIO
        
Resources:
    
    FileSystem:
      Type: AWS::EFS::FileSystem
      Properties:
        FileSystemTags:
        - Key: Name
          Value: !Ref AWS::StackName
        PerformanceMode: !Ref PerformanceMode
        
    MountTarget1:
      Type: AWS::EFS::MountTarget
      DependsOn:
      - FileSystem
      Properties:
        FileSystemId: !Ref FileSystem
        SubnetId: 
          Fn::ImportValue: !Sub "${EnvironmentName}-private-subnet-1"
        SecurityGroups:
        - Fn::ImportValue: !Sub "${EnvironmentName}-sg-mount-target"

    MountTarget2:
      Type: AWS::EFS::MountTarget
      DependsOn:
      - FileSystem
      Properties:
        FileSystemId: !Ref FileSystem
        SubnetId: 
          Fn::ImportValue: !Sub "${EnvironmentName}-private-subnet-2"
        SecurityGroups:
        - Fn::ImportValue: !Sub "${EnvironmentName}-sg-mount-target"

    
Outputs:

  FileSystem:
    Description: FileSystem
    Value: !Ref FileSystem
    Export: 
      Name: !Sub '${EnvironmentName}-efs-id'
    
  PerformanceMode:
    Description: PerformanceMode
    Value: !Ref PerformanceMode
