Description: >
    This template deploys an RDS needed for all the postgres databases.

Parameters:
    CompanyName:
        Description: Used to name space company buckets
        Type: String
        Default: transin
        
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: staging
    
    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the security groups should be deployed to
    
    PublicSubnet1:
        Type: AWS::EC2::Subnet::Id

    PublicSubnet2:
        Type: AWS::EC2::Subnet::Id
    
    # DBSubnetGroup:
    #     Type: AWS::RDS::DBSubnetGroup
    #     Default: staging-vpc-7sxfcu8m57ku-dbsubnetgroup-oa0n9fxxdmw0

    DBName:
        Type: String
        Default: transin
  
    DBEngine:
        Type: String
        Default: postgres

    DBEngineVersion:
        Type: String
        Default: '9.5.2'

    DBMasterUserName:
        Type: String
        Default: transin
    
    DBMasterUserPassword:
        Type: String
        Default: epoo9mohNg
    
    DBInstanceClass:
        Type: String
        Default: db.m4.large

    DBStorage:
        Type: String
        Default: '10'

    DBSecurityGroup:
        Type: AWS::EC2::SecurityGroup::Id
        Default: sg-fef6f599
    
    MultiAZDatabase:
        Type: String
        AllowedValues:
            - True
            - False
        Default: False

Resources:
    
    DBSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
          DBSubnetGroupDescription: Subnet group for Transin RDS db
          SubnetIds:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2

    DB:
        Type: AWS::RDS::DBInstance
        DeletionPolicy: Delete
        Properties:
          DBName: !Ref DBName
          Engine: !Ref DBEngine
          EngineVersion: !Ref DBEngineVersion
          MasterUsername: !Ref DBMasterUserName
          MasterUserPassword: !Ref DBMasterUserPassword
          DBInstanceClass: !Ref DBInstanceClass
          DBSubnetGroupName: !Ref DBSubnetGroup
          AllocatedStorage: !Ref DBStorage
          VPCSecurityGroups: 
          - !Ref DBSecurityGroup
  
Outputs:
    
    DBAddress:
        Description: address of database endpoint
        Value:
          Fn::GetAtt:
          - DB
          - Endpoint.Address
    
    DBPort:
        Description: database endpoint port
        Value:
          Fn::GetAtt:
          - DB
          - Endpoint.Port
