Description: >
    This template deploys an RDS needed for all the postgres databases.

Parameters:
    CompanyName:
        Description: Used to name space company buckets
        Type: String
        Default: transin
        
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: staging
    
    # DBSubnetGroup:
    #     Type: AWS::RDS::DBSubnetGroup
    #     Default: staging-vpc-7sxfcu8m57ku-dbsubnetgroup-oa0n9fxxdmw0

    DBName:
        Type: String
        Default: transin
  
    DBEngine:
        Type: String
        Default: postgres

    DBEngineVersion:
        Type: String
        Default: '9.5.2'

    DBMasterUserName:
        Type: String
        Default: transin
    
    DBMasterUserPassword:
        Type: String
        Default: epoo9mohNg
    
    DBInstanceClass:
        Type: String
        Default: db.m4.large

    DBStorage:
        Type: String
        Default: '10'
    
    MultiAZDatabase:
        Type: String
        AllowedValues:
            - True
            - False
        Default: False

Resources:
    
    DBSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
          DBSubnetGroupDescription: Subnet group for Transin RDS db
          SubnetIds:
            - Fn::ImportValue: !Sub "${EnvironmentName}-public-subnet-1"
            - Fn::ImportValue: !Sub "${EnvironmentName}-public-subnet-2"

    DB:
        Type: AWS::RDS::DBInstance
        DeletionPolicy: Delete
        Properties:
          DBName: !Ref DBName
          Engine: !Ref DBEngine
          EngineVersion: !Ref DBEngineVersion
          MasterUsername: !Ref DBMasterUserName
          MasterUserPassword: !Ref DBMasterUserPassword
          DBInstanceClass: !Ref DBInstanceClass
          DBSubnetGroupName: !Ref DBSubnetGroup
          AllocatedStorage: !Ref DBStorage
          VPCSecurityGroups: 
            - Fn::ImportValue: !Sub "${EnvironmentName}-sg-rds"
  
Outputs:
    
    DBAddress:
        Description: address of database endpoint
        Value:
          Fn::GetAtt:
          - DB
          - Endpoint.Address
        Export: 
            Name: !Sub '${EnvironmentName}-rds-address'

    DBPort:
        Description: database endpoint port
        Value:
          Fn::GetAtt:
          - DB
          - Endpoint.Port
        Export: 
            Name: !Sub '${EnvironmentName}-rds-port'

