Description: >
    This template creates cluster of redis over AWS ECS with persistance storage on EFS

Parameters:
    CompanyName:
        Description: Used to name space company buckets
        Type: String
        
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        
Resources:
   
                    
Outputs:

    